# Generated by Django 6.0.3 on 2026-05-03 11:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('icone', models.CharField(help_text="Nom de l'icône Bootstrap (ex: bi-lightbulb)", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('date_eval', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, help_text='Montant total payé par client (FCFA)', max_digits=10)),
                ('montant_prestataire', models.DecimalField(decimal_places=2, default=0, help_text='Montant net pour prestataire (FCFA)', max_digits=10)),
                ('montant_frais', models.DecimalField(decimal_places=2, default=0, help_text='Frais admin (3%) (FCFA)', max_digits=10)),
                ('methode', models.CharField(choices=[('flooz', 'Flooz (*155#)'), ('tmoney', 'Mix by Yas (*145#)')], default='flooz', max_length=50)),
                ('numero_client', models.CharField(default='', help_text='Numéro payeur', max_length=15)),
                ('numero_prestataire', models.CharField(default='', help_text='Numéro prestataire', max_length=15)),
                ('numero_admin', models.CharField(default='', help_text='Numéro admin frais', max_length=15)),
                ('transaction_ref', models.CharField(blank=True, default='', help_text='Référence paiement', max_length=20)),
                ('ussd_prestataire', models.CharField(blank=True, default='', help_text='Commande USSD prestataire', max_length=100)),
                ('ussd_admin', models.CharField(blank=True, default='', help_text='Commande USSD admin', max_length=100)),
                ('date_paiement', models.DateTimeField(auto_now_add=True, null=True)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('tx_reference_paygate', models.CharField(blank=True, default='', max_length=100)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('confirme', 'Confirmé'), ('echoue', 'Échoué')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(max_length=15)),
                ('adresse', models.TextField()),
                ('type_compte', models.CharField(choices=[('client', 'Client'), ('prestataire', 'Prestataire')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_acces', models.CharField(default='SuperAdmin', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reservation', 'Réservation'), ('chat', 'Chat'), ('paiement', 'Paiement'), ('systeme', 'Système')], default='systeme', max_length=20)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(max_length=100)),
                ('numero_flooz', models.CharField(blank=True, default='', help_text='Numéro Flooz (ex: 97430290)', max_length=15)),
                ('numero_mix', models.CharField(blank=True, default='', help_text='Numéro Mix by Yas (ex: 93354922)', max_length=15)),
                ('photo', models.ImageField(blank=True, help_text='Photo de profil du prestataire', null=True, upload_to='prestataires/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prestataire_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de l'atelier", max_length=200)),
                ('adresse', models.TextField(help_text="Adresse complète de l'atelier")),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude (ex: 6.125580)', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude (ex: 1.232456)', max_digits=9)),
                ('telephone', models.CharField(help_text="Numéro de téléphone de l'atelier", max_length=15)),
                ('description', models.TextField(blank=True, help_text='Description supplémentaire')),
                ('est_actif', models.BooleanField(default=True, help_text="L'atelier est-il actif?")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ateliers', to='service.prestataire')),
            ],
            options={
                'verbose_name': 'Atelier',
                'verbose_name_plural': 'Ateliers',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_res', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateTimeField(blank=True, help_text="Date et heure de début de l'intervention", null=True)),
                ('lieu', models.CharField(blank=True, default='', help_text="Lieu précis de l'intervention", max_length=300)),
                ('notes', models.TextField(blank=True, default='', help_text='Notes supplémentaires du client')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_attente_paiement', 'En attente de paiement'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='en_attente', max_length=25)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirmation', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='service.client')),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='service.evaluation')),
                ('paiement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_liee', to='service.paiement')),
            ],
            options={
                'ordering': ['-date_res'],
            },
        ),
        migrations.AddField(
            model_name='paiement',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiement_set_associes', to='service.reservation', verbose_name='Réservation liée'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='service.reservation')),
            ],
            options={
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilite', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, help_text='Image du service', null=True, upload_to='services/')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='service.categorie')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service.prestataire')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='service.service'),
        ),
    ]
