# Generated by Django 6.0.3 on 2026-05-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='model_3d',
            field=models.FileField(blank=True, help_text='Modèle 3D glTF pour AR Preview (optionnel)', null=True, upload_to='models_3d/'),
        ),
    ]
