# Generated by Django 6.0.3 on 2026-05-04 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_model_3d'),
        ('service', 'migration_fidelite'),
    ]

    operations = [
    ]
