# Generated by Django 6.0.3 on 2026-05-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_merge_0002_service_model_3d_migration_fidelite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointsfidelite',
            name='prestataire',
        ),
        migrations.DeleteModel(
            name='HistoriquePoints',
        ),
        migrations.DeleteModel(
            name='PointsFidelite',
        ),
    ]
