# Generated by Django 4.2.16 on 2026-06-17 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_compte_telephone_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Solde disponible pour retrait (FCFA)', max_digits=12),
        ),
        migrations.CreateModel(
            name='DemandeRetrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('methode', models.CharField(choices=[('flooz', 'Flooz'), ('tmoney', 'T-Money / Mix')], max_length=20)),
                ('numero_paiement', models.CharField(help_text="Numéro sur lequel recevoir l'argent", max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('notes_admin', models.TextField(blank=True, default='')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_retrait', to='service.prestataire')),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
    ]
