# Generated by Django 5.2.15 on 2026-06-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_prestataire_solde_demanderetrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='fonds_liberes',
            field=models.BooleanField(default=False, help_text='Les fonds ont-ils été libérés au prestataire ?'),
        ),
    ]
