# Generated by Django 5.2.15 on 2026-06-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_paiement_fonds_liberes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='statut_activite',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupé / En intervention'), ('hors_ligne', 'Hors ligne')], default='disponible', help_text="Statut d'activité en temps réel", max_length=20),
        ),
    ]
