# Generated by Django 5.2.15 on 2026-06-29 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_prestataire_statut_activite'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestatairePortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prestataires/portfolio/', verbose_name='Photo de réalisation')),
                ('description', models.CharField(blank=True, help_text='Ex: Rénovation salon de coiffure', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='service.prestataire', verbose_name='Prestataire lié')),
            ],
            options={
                'verbose_name': 'Réalisation du portfolio',
                'verbose_name_plural': 'Portfolio du prestataire',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/', verbose_name='Photo additionnelle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='service.service', verbose_name='Service lié')),
            ],
            options={
                'verbose_name': 'Image de service',
                'verbose_name_plural': 'Images de services',
            },
        ),
    ]
