# Generated by Django 5.2.15 on 2026-07-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_alter_compte_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='date_expiration_abonnement',
            field=models.DateTimeField(blank=True, help_text="Date d'expiration de l'abonnement", null=True),
        ),
        migrations.AddField(
            model_name='prestataire',
            name='type_abonnement',
            field=models.CharField(choices=[('gratuit', 'Gratuit'), ('pro', 'Pro'), ('prestige', 'Prestige')], default='gratuit', help_text="Type d'abonnement du prestataire", max_length=20),
        ),
    ]
