# Generated by Django 5.2.15 on 2026-07-01 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_signalement_favori'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='prestataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_abonnement', to='service.prestataire', verbose_name='Prestataire payeur'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='type_abonnement_vise',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Type d'abonnement visé"),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiement_set_associes', to='service.reservation', verbose_name='Réservation liée'),
        ),
    ]
