[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.install]
cmds = [
  "npm install",
  "pip3.11 install -r requirements.txt"
]

[phases.build]
cmds = [
  "CI=false npm run build",
  "python3.11 manage.py collectstatic --noinput"
]

[start]
cmd = "python3.11 manage.py migrate --noinput && daphne -b 0.0.0.0 -p $PORT service_market.asgi:application"

[variables]
PYTHONUNBUFFERED = "1"
NODE_ENV = "production"