[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate --noinput && daphne -b 0.0.0.0 -p $PORT service_market.asgi:application"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[healthcheck]
path = "/api/"
timeout = 30
